server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name ${DOMAIN_NAME};

    ssl_certificate /etc/ssl/certs/nginx.crt;
    ssl_certificate_key /etc/ssl/certs/nginx.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    
    # Ustawienie głównego katalogu
    root /var/www/html;
    index index.php index.html index.htm;

    # Ta lokalizacja obsługuje "ładne linki" (permalinks) WordPressa.
    location / {
        # Próbuje znaleźć plik/katalog, a jeśli się nie uda, przekazuje do index.php
        try_files $uri $uri/ /index.php?$args;
    }

    # KLUCZOWA SEKCJA: Obsługa plików .php
    # Wszystkie zapytania kończące się na .php trafiają tutaj
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        # Używamy kontenera wordpress (php-fpm) na porcie 9000
        fastcgi_pass wordpress:9000;
    }
}